<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Skight.AgentPlatform.FSharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="ToolRegistry.fs" />
    <Compile Include="AgentSession.fs" />
    <Compile Include="SdkAdapter.fs" />
    <Compile Include="AgentPipeline.fs" />
    <Compile Include="AgentRunner.fs" />
    <Compile Include="Agent.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.17" />
    <PackageReference Include="FSharp.Control.TaskSeq" Version="1.1.1" />
  </ItemGroup>

</Project>
